# Generated by Django 3.1.7 on 2022-02-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='key_skills',
            field=models.JSONField(default=''),
        ),
    ]
