# Generated by Django 4.0.1 on 2022-01-13 07:04

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_applicant_a_alter_applicant_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(max_length=254, upload_to=user.models.get_upload_path),
        ),
    ]
