# Generated by Django 3.1.7 on 2022-02-24 12:35

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220207_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='avi',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=user.models.get_avi_upload_path),
        ),
    ]
