# Generated by Django 3.1.7 on 2022-03-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_applicant_avi'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='avi_upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
