# Generated by Django 3.1.7 on 2022-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_applicant_avi_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='key_skills',
            field=models.JSONField(default=dict),
        ),
    ]
