# Generated by Django 3.1.7 on 2022-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_alter_personalitytraits_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitytraits',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
