# Generated by Django 4.0.1 on 2022-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20220316_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitytraits',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
